<?php

function shift_cipher_menu() {
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher!',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['shift_cipher_success_page'] = array(
        'title' => "Here's your coded phrase:",
        'page callback' => 'shift_cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function shift_cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value:',
        '#description' => 'Enter a value for the number of places you want to shift each letter over. ex: 3',
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );

    $form['direction'] = array(
        '#title' => 'Direction:',
        '#description' => 'Left or Right.',
        '#type' => 'textfield',
        '#element_validate' => array('shift_sipher_form_validate'),
        '#required' => TRUE,
    );

    $form['phrase'] = array(
        '#title' => 'Phrase:',
        '#description' => 'Enter the phrase you want to encrypt.',
        '#type' => 'textfield',
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'ENCRYPT IT!',
    );

    return $form;
}

function shift_sipher_form_validate($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $direction = strtolower($form_state['values']['direction']);
    $input = $form_state['values']['phrase'];

    if (($direction != 'left') && ($direction != 'right')) {
        form_set_error('', 'Sorry, you must pick either left or right.');
    }
}

function shift_cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['direction'];
    $phrase_input = explode(' ', strtolower($form_state['values']['phrase']));

    $encrypted_words = array();

    foreach ($phrase_input as $word) {
        $split_word = str_split($word);
        $numbered_phrase = array();

        foreach($split_word as $letter) {
            if (ctype_alpha($letter)) {
                $number_val = ord($letter);
                if ($direction == 'left') {
                    $shifted_number = $number_val - $shift_value;
                } else {
                    $shifted_number = $number_val + $shift_value;
                }

                if ($shifted_number > 122) {
                    $shifted_number -= 26;
                }
                if ($shifted_number < 97) {
                    $shifted_number += 26;
                }
                $converted_letter = chr($shifted_number);
                array_push($numbered_phrase, $converted_letter);
            } else {
                array_push($numbered_phrase, $letter);
            }
        }
        $encrypted_word = implode($numbered_phrase);

        array_push($encrypted_words, $encrypted_word);
    }
    $result = implode(' ', $encrypted_words);

    $_SESSION['testing'] = $phrase_input;
    $_SESSION['result'] = $result;
    $form_state['redirect'] = 'shift_cipher_success_page';

}

function shift_cipher_success() {
    // var_dump($_SESSION['result']);
    // var_dump($_SESSION['testing']);
    return '<h3>' . $_SESSION['result'] . '</h3>';
}
